//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/work", ReplyAction="http://tempuri.org/IService1/workResponse")]
        void work();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/work", ReplyAction="http://tempuri.org/IService1/workResponse")]
        System.Threading.Tasks.Task workAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListOfFilters", ReplyAction="http://tempuri.org/IService1/GetListOfFiltersResponse")]
        string[] GetListOfFilters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListOfFilters", ReplyAction="http://tempuri.org/IService1/GetListOfFiltersResponse")]
        System.Threading.Tasks.Task<string[]> GetListOfFiltersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference4.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference4.IService1>, Client.ServiceReference4.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void work() {
            base.Channel.work();
        }
        
        public System.Threading.Tasks.Task workAsync() {
            return base.Channel.workAsync();
        }
        
        public string[] GetListOfFilters() {
            return base.Channel.GetListOfFilters();
        }
        
        public System.Threading.Tasks.Task<string[]> GetListOfFiltersAsync() {
            return base.Channel.GetListOfFiltersAsync();
        }
    }
}
