//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference15 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference15.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/work", ReplyAction="http://tempuri.org/IService1/workResponse")]
        void work();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/work", ReplyAction="http://tempuri.org/IService1/workResponse")]
        System.Threading.Tasks.Task workAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListOfFilters", ReplyAction="http://tempuri.org/IService1/GetListOfFiltersResponse")]
        string[] GetListOfFilters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListOfFilters", ReplyAction="http://tempuri.org/IService1/GetListOfFiltersResponse")]
        System.Threading.Tasks.Task<string[]> GetListOfFiltersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ApplyFilter", ReplyAction="http://tempuri.org/IService1/ApplyFilterResponse")]
        System.Drawing.Bitmap ApplyFilter(System.Drawing.Bitmap image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ApplyFilter", ReplyAction="http://tempuri.org/IService1/ApplyFilterResponse")]
        System.Threading.Tasks.Task<System.Drawing.Bitmap> ApplyFilterAsync(System.Drawing.Bitmap image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProgress", ReplyAction="http://tempuri.org/IService1/GetProgressResponse")]
        int GetProgress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProgress", ReplyAction="http://tempuri.org/IService1/GetProgressResponse")]
        System.Threading.Tasks.Task<int> GetProgressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewImage", ReplyAction="http://tempuri.org/IService1/GetNewImageResponse")]
        int GetNewImage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewImage", ReplyAction="http://tempuri.org/IService1/GetNewImageResponse")]
        System.Threading.Tasks.Task<int> GetNewImageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference15.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference15.IService1>, Client.ServiceReference15.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void work() {
            base.Channel.work();
        }
        
        public System.Threading.Tasks.Task workAsync() {
            return base.Channel.workAsync();
        }
        
        public string[] GetListOfFilters() {
            return base.Channel.GetListOfFilters();
        }
        
        public System.Threading.Tasks.Task<string[]> GetListOfFiltersAsync() {
            return base.Channel.GetListOfFiltersAsync();
        }
        
        public System.Drawing.Bitmap ApplyFilter(System.Drawing.Bitmap image) {
            return base.Channel.ApplyFilter(image);
        }
        
        public System.Threading.Tasks.Task<System.Drawing.Bitmap> ApplyFilterAsync(System.Drawing.Bitmap image) {
            return base.Channel.ApplyFilterAsync(image);
        }
        
        public int GetProgress() {
            return base.Channel.GetProgress();
        }
        
        public System.Threading.Tasks.Task<int> GetProgressAsync() {
            return base.Channel.GetProgressAsync();
        }
        
        public int GetNewImage() {
            return base.Channel.GetNewImage();
        }
        
        public System.Threading.Tasks.Task<int> GetNewImageAsync() {
            return base.Channel.GetNewImageAsync();
        }
    }
}
